// Generated by scripts/generate-i18n-runtime.mjs. Edit i18n/config.json instead.
export const RUNTIME_LOCALES = ["en","ja","es","pt-BR","fr","de","ko","zh-Hans","zh-Hant","id","hi","ar"] as const;
export const RUNTIME_LOCALE_LABELS: Record<string, string> = {
  "en": "English",
  "ja": "日本語",
  "es": "Español",
  "pt-BR": "Português (Brasil)",
  "fr": "Français",
  "de": "Deutsch",
  "ko": "한국어",
  "zh-Hans": "简体中文",
  "zh-Hant": "繁體中文",
  "id": "Bahasa Indonesia",
  "hi": "हिन्दी",
  "ar": "العربية"
};
export const RUNTIME_LOCALE_ALIASES: Record<string, string> = {
  "ja-JP": "ja",
  "pt": "pt-BR",
  "pt-PT": "pt-BR",
  "zh": "zh-Hans",
  "zh-CN": "zh-Hans",
  "zh-SG": "zh-Hans",
  "zh-TW": "zh-Hant",
  "zh-HK": "zh-Hant",
  "zh-MO": "zh-Hant"
};
export const RUNTIME_RTL_LOCALES = ["ar"] as const;
