import assert from 'node:assert/strict';
import { buildKnowledgeGraph, projectKnowledge, remapKnowledgeRelations } from '../src/galaxy/knowledgeGraph.ts';
import type { AtlasNode } from '../src/types.ts';
import type { SpaceView } from '../src/galaxy/galaxySummary.ts';
import { knowledgeMetrics, knowledgeCascade } from '../src/galaxy/knowledgePresentation.ts';
const node = (id: string, title: string, children: AtlasNode[] = []): AtlasNode => ({ id, title, body: `${title} shared evidence research`, summary: '', tags: [], children } as unknown as AtlasNode);
const a = node('same-id', 'Research', [node('a', 'Shared research evidence')]);
const b = node('same-id', 'Product', [node('b', 'Shared research evidence')]);
const views = [{ space: { id: 's1', dependsOn: ['s2'] }, root: a }, { space: { id: 's2', dependsOn: ['s1'] }, root: b }] as SpaceView[];
const graph = buildKnowledgeGraph(views);
assert.equal(new Set(graph.nodes.map(n => n.key)).size, 4, 'IDs are space scoped');
assert.equal(graph.relations.filter(r => r.source === 'dependency').length, 2);
const candidate = graph.relations.find(r => r.source === 'candidate')!;
assert.ok(candidate);
const judgment = { ...candidate, type: 'supports' as const, source: 'ai' as const, confidence: .82, model: 'test-fixture' };
assert.ok(buildKnowledgeGraph(views, [judgment]).relations.some(r => r.source === 'ai'));
const mutated = graph.nodes.find(n => n.key === judgment.from)!;
mutated.node.body = 'Changed evidence';
assert.ok(!buildKnowledgeGraph(views, [judgment]).relations.some(r => r.source === 'ai'), 'Edits retract obsolete AI judgments');
const projection = projectKnowledge(graph, 'research', 'all');
assert.ok(projection.nodes.size <= graph.nodes.length, 'Cycles terminate');
assert.ok(projection.tree.length <= graph.nodes.length - projection.seeds.size, 'Projection never re-adds visited nodes');
assert.equal(projectKnowledge(graph, 'no-such-query', 'all').nodes.size, 0);
const removed = buildKnowledgeGraph([{ ...views[0], root: node('same-id', 'Research') }]);
assert.ok(removed.relations.every(r => removed.nodes.some(n => n.key === r.from) && removed.nodes.some(n => n.key === r.to)), 'No dangling references after deletion');
const c = node('c', 'Third notebook');
const chainViews = [{space:{id:'s1',dependsOn:['s2']},root:a},{space:{id:'s2',dependsOn:['s3']},root:b},{space:{id:'s3',dependsOn:[]},root:c}] as SpaceView[];
const chain=buildKnowledgeGraph(chainViews);
const inferred=chain.relations.find(r=>r.source==='inference')!;
assert.equal(inferred.supportIds?.length,2,'Derived dependency keeps its premises');
assert.ok(!buildKnowledgeGraph([{...chainViews[0],space:{...chainViews[0].space,dependsOn:[]}},...chainViews.slice(1)]).relations.some(r=>r.source==='inference'),'Removing a premise retracts inferred dependencies');
const imported=remapKnowledgeRelations([judgment,{...judgment,type:'invented'},null],id=>`import-${id}`);
assert.equal(imported.length,1,'Import rejects unsupported relation types');
assert.equal(JSON.parse(imported[0].from)[0],`import-${JSON.parse(judgment.from)[0]}`,'Import remaps scoped endpoints');
assert.ok(projectKnowledge(chain,'何が必要なのか','all').active,'Bounded question intents activate a projection');
const parent=graph.nodes.find(n=>n.depth===0)!;
const child=graph.nodes.find(n=>n.parentKey===parent.key)!;
child.node.status='done';parent.node.status='blocked';
assert.deepEqual(knowledgeMetrics(graph).get(parent.key),{count:2,done:1,blocked:1,review:0,running:0},'Status arcs aggregate canonical descendants exactly once');
const forest=knowledgeCascade(graph,[parent.key,parent.key,'missing']);
const collect=(items:ReturnType<typeof knowledgeCascade>):string[]=>items.flatMap(item=>[item.key,...collect(item.children)]);
const visited=collect(forest);
assert.equal(forest.length,1,'Invalid and duplicate roots are omitted');
assert.equal(visited.length,new Set(visited).size,'Cycles and cross-links never duplicate tree items');
assert.ok(visited.length<=80);
assert.equal(collect(knowledgeCascade(graph,[parent.key],new Set())).length,1,'Relation filtering restricts traversal');
console.log('Knowledge graph: scoped IDs, stale-source retraction, cycles, deletion, inference provenance/retraction, import and question intents passed.');
